name: Migrate your Prisma schema to sqlite
on:
  push:

jobs:
  migrate-sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use PNPM 7.12
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.0

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Run migration script
        run: node ./.github/actions/prisma-transformer/index.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push schema
        run: npx prisma db push --schema="prisma/_sqlite/schema.prisma"

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Build
        run: pnpm build
